import argparse
from pathlib import Path

from modules.perception.tracking_log_analyzer import analyze_tracking_log, format_analysis_report


def build_report(summary):
    return format_analysis_report(summary)


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze ArUco visual tracking dry-run CSV logs.")
    parser.add_argument(
        "log",
        nargs="?",
        default="logs/aruco_tracking_dryrun.csv",
        help="CSV log path generated by tools/run_aruco_tracking_dryrun.py",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    summary = analyze_tracking_log(Path(args.log))
    print(build_report(summary))


if __name__ == "__main__":
    main()
